#Packages installation
    - name: Install nginx Packages
      yum: name=nginx update_cache=yes state=latest

  # Nginx Configuration

   - name: Sets Nginx conf file
     template:
       src: "files/lemp-nginx.conf"
       dest: "/etc/nginx/conf.d/{{ http_conf }}"

   - name: Removes "default" site
     file:
       path: "/etc/nginx/conf.d/default"
       state: absent
     notify: Reload Nginx
